### ISSUE TITLE
Permit disable actions on role permissions

### ISSUE THREAD

**Issue by stefsava** [marmelab/aor-permissions#13]
I have a project with admin-on-rest where I need to condition permissions granted to the user, through the roles, to enable or disable the created, delete, edit, show and list actions.

The aor-permissions component does not seem to allow this.
I just managed to disable the buttons in the list, but of course, if you disable, for example, the delete in the list, it still appears in the show.
The ideal would be to act when defining the resource with something like this code:

``` javascript
import React from 'react';
import { simpleRestClient, Admin, Resource, Delete } from 'admin-on-rest';
import { can } from 'aor-roles';

import { PostList, PostCreate, PostEdit, PostShow } from './posts';

const App = () => (
  <AuthProvider authClient={authClient}>
    <Admin restClient={simpleRestClient('http://path.to.my.api')}>
      <Resource
        name="posts"
        list={can('posts.list') && PostList}
        create={can('posts.create') && PostCreate}
        edit={can('posts.edit') && PostEdit}
        show={can('posts.show') && PostShow}
        remove={can('posts.remove') && Delete}
      } />
    </Admin>
  </AuthProvider>
);

export default App;
```
I did not find a method to let inject a function like can over it to be re-evaluated after a disconnect and a connect of another user with different permissions.

**Comment by djhi** [comment]
The problem with this approach is that `can` is asynchronous as the authClient function returns a promise. I'm investigating another way in #22
