### ISSUE TITLE
Permit Resource declaration based on permision

### ISSUE THREAD

**Issue by prakashjais99** [marmelab/aor-permissions#18]
Can we have something like below. So that we can declare  resources at higher instead of multiple edit/create layout for same resource

`<SwitchResourceWithPermission>
  <Permission value="admin">
    <Resource name="user" create={} edit={} list={}>
  </Permission>
  <Permission value="user">
    <Resource name="user" list={}>
  </Permission>
</SwitchResourceWithPermission>`

**Comment by djhi** [comment]
Please see and comment https://github.com/marmelab/aor-permissions/pull/22

**Comment by djhi** [comment]
Duplicate of #13
