### ISSUE TITLE
Usage on List Filter

### ISSUE THREAD

**Issue by ismailbaskin** [marmelab/aor-permissions#19]
Is there a way for hiding/showing some filter inputs based on role/permission?

**Comment by djhi** [comment]
Not currently. We're working on a solution

**Comment by djhi** [comment]
Not currently. We're working on a solution

**Comment by djhi** [comment]
We are working on integrating this addon into the core admin-on-rest package. I have proposed a solution for this particular problem here too. 

See https://github.com/marmelab/admin-on-rest/pull/959

**Comment by djhi** [comment]
It has been merged! It will be available in `1.3.0`. Hope you'll enjoy it!

**Comment by djhi** [comment]
**This project is discontinued. Its features have been merged in admin-on-rest 1.3.0. See [admin-on-rest documentation](https://marmelab.com/admin-on-rest/Authorization.html)**
