### ISSUE TITLE
Routing Issues with permissions

### ISSUE THREAD

**Issue by kodepareek** [marmelab/aor-permissions#9]
Hello

Firstly, thanks for this fantastic package. Has been tremendously useful. 

**Issue**: 

My App.js 

```
  <Admin menu={Menu} authClient={authClient} restClient={uploadCapableRESTClient}>
    <Resource name="appUsers" list={UserList} edit={AdminUserEdit} options={{ label: 'Users' }} />
    <Resource name="trackTale" list={BrandEditorTaleTrack} edit={EditTale} />
    <Resource name="tales" list={ AllEditorTaleDisplaySwitch } edit={EditTale} options={{ label: 'Assigned Tales' }}/>
</Admin>

```

In my custom Menu I am showing only role related links appropriately. 
For user Admin the first route is /appusers
For user Editor the first route displayed is /tales. 

When logging in as Editor however the app goes to the first route /appusers and since this user has no components attached to this route, the page only displays the menu. After clicking on the menu all behaviour is as expected. 

Look into it when can.

**Comment by djhi** [comment]
Hi, thanks for reporting this. I never had the problem as I only tested the addon on the admin-on-rest demo which has a dashboard. I'll see if we can do something about this.

In the meantime, there are two possible workarounds:

- add a [Dashboard](https://marmelab.com/admin-on-rest/Admin.html#dashboard) component
- a [custom saga](https://marmelab.com/admin-on-rest/Admin.html#customsagas) which would take the latest `USER_LOGIN_SUCCESS` action and redirect the user accordingly

**Comment by kodepareek** [comment]
Custom Sagas is a great idea. I will do that. Don't really have a 1 size fits all dashboard

**Comment by kodepareek** [comment]
Hi Guys. 

Have been trying this for a while today with this saga

const permission = localStorage.getItem('permissions')
```

function* userLoginSuccess() {
  if (permission === 'publishing') {
    yield put(push('/tales'))
  } else {
    yield put(push('/tales/talesByRelation'))
  }
}

export default function* userLoginSaga() {
  yield all ([
    takeEvery('AOR/USER_LOGIN_SUCCESS', userLoginSuccess),
  ])
}

```

But no redirect happens. I get a warning from the SwitchPermissionsComponent 

> 
setState(…): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op



Please do advise.

**Comment by djhi** [comment]
Can you provide a codepen reproducing the issue ?

**Comment by djhi** [comment]
Maybe the new release with permissions on Resources can help you with that now ?
